- name: Starting ZAP
  hosts: zapservers
  remote_user: ubuntu
  gather_facts: no
  become: yes
  tasks:
  - name: running owasp zap container
    docker_container:
      name: owasp-zap
      image: owasp/zap2docker-stable
      interactive: yes
      state: started
      user: zap
      command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      ports:
        - "8090:8090"
