---
#export ANSIBLE_CACHE_PLUGIN=jsonfile
#export ANSIBLE_CACHE_PLUGIN_CONNECTION="~/ansiblefactcache"
#rm ~/ansiblefactcache/webserver
#ansible-playbook -i inventory.ini deploy.yaml
     
- name: Setup webserver
  hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3    
    allow_world_readable_tmpfiles: true
    dbserver_private_ip: "localhost"
    mysql_db_user: "photogallery"
    mysql_db_password: "photogallery123"
    mysql_root_password: "photogallery123"
    mysql_db_name: "mydb"
    mysql_remote_ip: "%"
  roles:
    - role: 'roles/webserver'
      tags: ['webserver']      
   
